title: Mostafa Okasha
email: mostafa@okasha.me

description: >-
  Mechatronics Engineering Graduate with Computer Science Focus

baseurl: ""
markdown: kramdown
github_username: MostafaOkasha

timezone: America/New_York
repository: MostafaOkasha/MostafaOkasha.github.io

logo: /images/
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

seo:
  name: Mostafa Okasha
  type: Person
url: https://okasha.me
twitter:
  username: MostafaOkasha
social:
  name: Mostafa Okasha
  links:
    - https://www.facebook.com/YourAwesomeKing
    - https://github.com/MostafaOkasha
    - https://www.linkedin.com/in/okashm/


